### ISSUE TITLE
Rclone set up

### ISSUE THREAD

**Issue by brianpenghe** [cellgeni/docs#19]
Just a suggestion: Dave Holland asked us to run a command before using rclone
![image](https://user-images.githubusercontent.com/4110443/226064436-4f2adffb-af30-4d3d-8122-c8f26b3b2e3e.png)

Could this be added to this instruction document?
https://github.com/cellgeni/docs/blob/master/docs/source/rclone.rst

Thanks!

**Comment by just-simon-5** [comment]
Hi @brianpenghe,

Sorry for the late update. This should be added in our next pull request.

Thanks!
Simon

**Comment by brianpenghe** [comment]
Thanks for updating. He suggested that `1.60.1` is now installed.

![image](https://github.com/cellgeni/docs/assets/4110443/6fac8ae0-2b7e-41a4-831b-e922a33fabd6)
